### ISSUE TITLE
In BO, Display name of the module

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/fontmanager#1]
The name of the module should be “Font manager” instead of “PrestaShop font manager”

**Comment by ramtin2025** [comment]
Name of the module is : "Multilingual font manager"

**Comment by robylr** [comment]
thanks.
I try to install but i don't see on BO.
I would like to change font.  Presta 1.7.4.2

really thanks

**Comment by ramtin2025** [comment]
> thanks.
> I try to install but i don't see on BO.
> I would like to change font. Presta 1.7.4.2
> 
> really thanks

You have to upload your fonts on (Multilingual font manager) module configuration page for your language. Then you can see changes on BO or FO depend on your action.
Don't forget to clear cache.
