### ISSUE TITLE
Display of configuration of the module in BO 

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/fontmanager#2]
Currently after the installation, the module add a dedicated page here : 
International > Font manager. 
We shouldn't have a dedicated page created in BO. 
In BO, the module should be configurable like others thanks to the configure state on the button module and not creating a dedicated page.

Shouldn't be like that : 
![configure](https://user-images.githubusercontent.com/40759259/46299941-cb3dd100-c5a2-11e8-81e4-46c8d35f2c06.png)
Should be configurable like that : 
![goodconfigure](https://user-images.githubusercontent.com/40759259/46299944-cc6efe00-c5a2-11e8-8795-f4088988a351.png)

**Comment by ramtin2025** [comment]
It's done on commit b9692dec91463da376bd764bb356302e76849496

**Comment by BilalDr** [comment]
Thanks @ramtin2025 but now when i click on configure it throw an error 500. Is it the same for you ?

**Comment by ramtin2025** [comment]
What is your PrestaShop version?
I don't have problem on PS(1.7.4.1 to 1.7.4.3 and 1.6.1.16 to 1.6.1.20).
Do you reset the module?

**Comment by ramtin2025** [comment]
> It's 1.7.4.2, when i click on Configure there is the error : Page not found
> ![image](https://user-images.githubusercontent.com/40759259/46420064-85624380-c72f-11e8-8edf-8c4594c5f9bb.png)

I checked it again and there was no problem. May you retry on fresh install ?
