### ISSUE TITLE
In BO, language name instead of ISO Code 

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/fontmanager#3]
Not a critical issue : 
Instead of writing ISO code it could be better to have the name of the languages. 
![languageiso](https://user-images.githubusercontent.com/40759259/46300034-03451400-c5a3-11e8-81c7-dd248af94c75.png)
We should have for example : French instead of FR

**Comment by mehrshadz** [comment]
Actually we used ISO instead of full name to prevent it become 2 lines or 2 rows (we made it shorter)
